name: focora
description: Um aplicativo anti-procrastinação baseado em ciência cognitiva.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.0.5
  uuid: ^3.0.7
  intl: ^0.18.1
  flutter_dotenv: ^5.1.0
  fl_chart: ^0.63.0
  get_it: ^7.6.0
  google_fonts: ^4.0.4
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  test: ^1.24.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env.development
    - .env.testing
    - .env.production
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
